apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jobpoolv2
  name: nginx-conf
data:
  nginx.conf: |
    user  root;
    worker_processes  1;

    #error_log  logs/error.log;
    #error_log  logs/error.log  notice;
    #error_log  logs/error.log  info;

    #pid        logs/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        # 隐藏版本信息
        server_tokens off;
        include       mime.types;
        default_type  application/octet-stream;

        #access_log  logs/access.log main;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout 0;
        keepalive_timeout 120s;
        client_header_timeout 120s;
        client_body_timeout 120s;
        client_max_body_size 1024m;

        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        gzip on;
        gzip_min_length 1000;
        gzip_buffers 4 8k;
        gzip_types text/plain application/x-javascript text/css application/json application/xml text/javascript application/javascript;

        server {
            listen  30087;
            server_name  localhost;

            #charset koi8-r;
            set $jobpool_upstream http://jobpool-handless.jobpoolv2:2379;

            location / {
                add_header Access-Control-Allow-Origin  *;
                add_header Access-Control-Allow-Headers X-Requested-With;
                add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,PATCH,OPTIONS;

                root   html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
            
            location /v3 {
                resolver 127.0.0.1:53 ipv6=off valid=10s;
                proxy_pass  $jobpool_upstream;
                proxy_http_version 1.1;
            }
    
            location /pdf/ {
                valid_referers server_names ~.;
                if ($invalid_referer) {
                    #盗链时返回404
                    return 404;
                }
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jobpoolv2
  annotations:
    deployment.kubernetes.io/revision: '1'
  generation: 1
  labels:
    app: nginx-service-deployment
  name: nginx-service-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-service-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-service-deployment
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - name: nginx-service-deployment
          image: registry.cn-beijing.aliyuncs.com/yunli-data-platform/jobpool-nginx:2.0.0-SNAPSHOT.x86_64
          imagePullPolicy: Always
          resources:
            limits:
              memory: 320Mi
            requests:
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
        - name: dnsmasq
          image: registry.cn-beijing.aliyuncs.com/yunli-data-platform/go-dnsmasq:1.0.7.x86_64
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
      volumes:
        - configMap:
            name: nginx-conf
          name: nginx-conf

---

apiVersion: v1
kind: Service
metadata:
  namespace: jobpoolv2
  name: nginx-service
spec:
  ports:
    - nodePort: 30087
      port: 30087
      protocol: TCP
      targetPort: 30087
  selector:
    app: nginx-service-deployment
  sessionAffinity: None
  type: NodePort
