apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  namespace: jobpoolv2
  name: aliyun
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1iZWlqaW5nLmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6InpoZW5nd2VpQDEyODA4MzY4MTUyMjg4NDYiLCJwYXNzd29yZCI6InpoZW5nd2VpMTIzIiwiYXV0aCI6ImVtaGxibWQzWldsQU1USTRNRGd6TmpneE5USXlPRGcwTmpwNmFHVnVaM2RsYVRFeU13PT0ifX19
---
apiVersion: v1
kind: Service
metadata:
  name: jobpool-handless
  namespace: jobpoolv2
  labels:
    app: jobpool2
spec:
  clusterIP: None
  ports:
    - port: 2380
      name: peer
    - port: 2379
      name: client
    - port: 4001
      name: client2
  selector:
    app: jobpool2
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: jobpool2
  name: jobpool2
  namespace: jobpoolv2
spec:
  replicas: 3
  serviceName: jobpool-handless
  selector:
    matchLabels:
      app: jobpool2
  template:
    metadata:
      labels:
        app: jobpool2
    spec:
      imagePullSecrets:
        - name: aliyun
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: jobpoolv2 #node节点的标签
                    operator: In
                    values:
                      - serverv2
      volumes:
        - name: local-data-dir
          hostPath:
            path: /data/jobpool-v2-develop
      containers:
        - name: jobpool2
          image: registry.cn-beijing.aliyuncs.com/yunli-data-platform/jobpool-v2:2.0.0-SNAPSHOT.x86_64
          imagePullPolicy: Always
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.25"
          ports:
            - containerPort: 4001
            - containerPort: 2380
            - containerPort: 2379
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_LOG_LEVEL
              value: info
            - name: ETCD_DATA_DIR
              value: "/var/lib/etcd/default.etcd"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(HOST_IP):2379,http://$(HOST_IP):4001,http://jobpool-handless.$(NAMESPACE).svc.cluster.local:4001"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379,http://0.0.0.0:4001"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(HOST_IP):2380"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"
            - name: ETCD_INITIAL_CLUSTER
              value: "jobpool2-0=http://jobpool2-0.jobpool-handless.$(NAMESPACE).svc.cluster.local:2380,jobpool2-1=http://jobpool2-1.jobpool-handless.$(NAMESPACE).svc.cluster.local:2380,jobpool2-2=http://jobpool2-2.jobpool-handless.$(NAMESPACE).svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "jobpool2-0"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_EXPERIMENTAL_WARNING_APPLY_DURATION
              value: "500ms"
          volumeMounts:
            - name: local-data-dir
              mountPath: /var/lib/etcd
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: jobpoolv2
  name: jobpool-cluster-service
spec:
  ports:
    - nodePort: 30088
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: jobpool2
  sessionAffinity: None
  type: NodePort