apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-1
  namespace: etcd357
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-etcd-sample
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  k8s-worker1
---        
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-2
  namespace: etcd357
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-etcd-sample
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  k8s-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-3
  namespace: etcd357
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-etcd-sample
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          -  k8s-worker3     
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  namespace: etcd357
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer